package tk.daporkchop.mcstatuschecker;

public final class HTML {
	public static final String indexOnline = "<html><head>"
			+ "<link type=\"text/css\" rel=\"stylesheet\" href=\"http://www.daporkchop.tk/stylesheet.css\"/>"
			+ "<title>Is INSNAME down?</title>" + "</head>" + "<body><strong><h1>INSNAME status checker</h1></strong>\n"
			+ "<div id=\"contentBox\" style=\"margin:0px auto; width:100%\">"
			+ "<div id=\"column1\" style=\"float:left; margin:2; width:INSDIVSTYLE1\">"
			+ "INSFAVICON<p></p><h2>INSNAME status: </h2></p><strong><i><h3 style=\"color:"
			+ "INSSTATE"
			+ "</h3></i></strong></div>"
			+ "<p style=\"display:inline\">&nbsp;&nbsp;&nbsp;</p><div id=\"column2\" style=\"float:left; margin:2; width:INSDIVSTYLE1\">"
			+ "<h2>MOTD:</h2><strong><i><h3>INSMOTD</h3></i></strong><p></p>"
			+ "<h2>Version:</h2><strong><i><h3>INSVERSION</h3></i></strong>"
			+ "</div>"
			+ "<p style=\"display:inline\">&nbsp;&nbsp;&nbsp;</p><div id=\"column3\" style=\"float:left; margin:2; width:INSDIVSTYLE1\">"
			+ "<h2>Player count:</h2><strong><i><h3>INSONLINE/INSMAX</h3></i></strong><p></p>"
			+ "</div></div>"
			+ "<img src=\"data:image/png;base64,INSGRAPH\"></img>"
			+ "<p></p>"
			+ "<h3>Servers I'm tracking:</h3>"
			+ "INSSERVERS<p></p>"
			+ "<p>This is still very much WIP. Send me features <a href=\"https://github.com/DaMatrix/2b2tTracker/issues\">here</a> and I'll do my best to implement them!</p>"
			+ "<p>Note: The graph sometimes appears to be missing data if the webserver has just been started. Also, it only updates every 10 mins.</p>"
			+ "<iframe src=\"http://www.daporkchop.tk/toembed/adrefresh.html\" scrolling='no' style='width:740px; height:105px; border:0px; padding:0;overflow:hidden' allowtransparency='true' frameborder='0'></iframe></body></html>\n";
	public static final String indexOffline = "<html><head>"
			+ "<link type=\"text/css\" rel=\"stylesheet\" href=\"http://www.daporkchop.tk/stylesheet.css\"/>"
			+ "<title>Is INSNAME down?</title>" + "</head>" + "<body><strong><h1>INSNAME status checker</h1></strong>\n"
			+ "<div id=\"contentBox\" style=\"margin:0px auto; width:100%\">"
			+ "<div id=\"column1\" style=\"float:left; margin:2; width:INSDIVSTYLE1\">"
			+ "INSFAVICON<p></p><h2>INSNAME status: </h2></p><strong><i><h3 style=\"color:"
			+ "INSSTATE"
			+ "</h3></i></strong></div>"
			+ "</div>"
			+ "<img src=\"data:image/png;base64,INSGRAPH\"></img>"
			+ "<p></p>"
			+ "<h3>Servers I'm tracking:</h3>"
			+ "INSSERVERS<p></p>"
			+ "<p>This is still very much WIP. Send me features <a href=\"https://github.com/DaMatrix/2b2tTracker/issues\">here</a> and I'll do my best to implement them!</p>"
			+ "<p>Note: The graph sometimes appears to be missing data if the webserver has just been started. Also, it only updates every 10 mins.</p>"
			+ "<iframe src=\"http://www.daporkchop.tk/toembed/adrefresh.html\" scrolling='no' style='width:740px; height:105px; border:0px; padding:0;overflow:hidden' allowtransparency='true' frameborder='0'></iframe></body></html>\n";
}
